[package]
name = "modular_agents"
version = "0.1.0"
edition = "2021"

[dependencies]

# Optimizations for small binary
# [profile.release]
# opt-level = "z"  # Optimize for size.
# lto = true
# codegen-units = 1
# strip = true  # Automatically strip symbols from the binary.
# panic = "abort"